name: RubyGem CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.x # Adjust to your Ruby version

    - name: Install Dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build Gem
      run: |
        gem build eskomsepush_ruby.gemspec

    - name: Install Gem Locally
      run: |
        gem install ./eskomsepush_ruby-*.gem

    - name: Run RSpec
      run: |
        bundle exec rspec